language: rust

addons:
  apt:
    update: true
    packages:
      - binutils-dev
      - libunwind8-dev
      - libzmq3-dev


matrix:
  include:
    - rust: nightly
      env: AS_DEPENDENCY=true DO_LINT=true

script:
  - ./contrib/test.sh
