[package]
name = "internet2"
version = "0.3.10"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Rust implementation for the stack of Internet2 protocols"
repository = "https://github.com/internet2-org/rust-internet2"
homepage = "https://github.com/internet2-org"
keywords = ["internet2", "tor", "noise-xk", "privacy", "cryptography"]
categories = ["network-programming", "cryptography", "encoding"]
readme = "README.md"
edition = "2018"
exclude = [".github", "derive", "contrib", "microservices", "addr"]

[lib]
name = "internet2"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

# Dependencies
# ============
[dependencies]
# Dependencies on other LNP/BP repositories
# -----------------------------------------
amplify = { version = "3", features = ["stringly_conversions"] }
amplify_derive = "2.4.4"
strict_encoding = { version = "1", default-features = false, features = ["derive"] }
lightning_encoding = "0.4.0-beta.1"
inet2_addr = { version = "0.4", features = ["strict_encoding", "stringly_conversions"] }
inet2_derive = { version = "0.4", default-features = false, optional = true }
# Dependencies on core rust-bitcoin & cryptography
# ------------------------------------------------
bitcoin = { version = "0.26", default-features = false, features = ["rand"] }
chacha20poly1305 = "0.7"
# Core rust projects
# ------------------
# This strange naming is a workaround for cargo inability to define required
# features for a dependency. See
# <https://github.com/rust-lang/api-guidelines/issues/180> for the explanation
# and references.
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
serde_with_macros = { version = "1.2", optional = true } # Fix for the problem in 1.3.0
lazy_static = "1.4"
# Networking deps
# ---------------
# These dependencies are used to provide support for networking URLs in
zmq = { version = "0.9", optional = true }
url = { version = "2", optional = true }

[dev-dependencies]
torut = { version = "0.1", features = ["v2", "v3"] }

[target.'cfg(target_os="android")'.dependencies]
zmq = { version = "0.9", features = ["vendored"], optional = true }

[target.'cfg(target_os="ios")'.dependencies]
zeromq-src = { version = "0.1", git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake", optional = true }

[target.'cfg(target_os="windows")'.dependencies]
openssl = { version = "0.10", features = ["vendored"], optional = true }

# Features
# ========
[features]
# Listings
# --------
#   By default we use LNP with Tor support and URL support
default = ["tor", "url", "zmq", "derive"]
all = ["derive",
       # Serde
       "serde", "keygen",
       # Networking
       "tor", "url", "zmq", "websockets", "vendored_openssl"]
# Exposing core rust componens
# ----------------------------
#   These also include re-assembly of necessary features from dependencies
serde = ["serde_crate", "serde_with", "serde_with_macros", "amplify/serde",
         "bitcoin/use-serde", "inet2_addr/serde"]
derive = ["inet2_derive"]
keygen = ["bitcoin/rand"]
# Networking
# ----------
websockets = []
tor = ["inet2_addr/tor"]
vendored_openssl = ["inet2_addr/vendored_openssl"]

[workspace]
members = [".", "derive", "addr", "microservices"]
default-members = [".", "derive", "addr", "microservices"]
exclude = ["dep_test"]
