name: Publication

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - run: cd derive && cargo publish --all-features
      - run: sleep 30; cargo publish --all-features
      - run: sleep 30; cd services && cargo publish --all-features
